 export const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  };

 export const setPoolNames = (poolId: number) => {
    const poolNames = [
      "Core Cascade",
      "Core Current",
      "Core Vortex",
      "Core Nexus",
      "Core Horizon",
      "Core Pulse",
      "Core Tide",
      "Core Forge",
      "Core Spark",
      "Core Vault",
      "Core Nexus",
      "Core Ascent",
      "Core Zenith",
      "Core Orbit",
      "Core Prism",
      "Core Matrix",
      "Core Infinity",
      "Core Genesis",
      "Core Epoch",
      "Core Nova",
      "Bitcoin Bay",
      "Satoshi Stream",
      "Halving Harbor",
      "Blockstream Basin",
      "Lightning Lagoon",
      "Hashrate Haven",
      "Mining Mirage",
      "Blockchain Bluff",
      "Crypto Cove",
      "Digital Delta",
      "Ledger Lagoon",
      "Node Nook",
      "Wallet Waters",
      "Genesis Gulf",
      "Fork Fjord",
      "Block Bay",
      "Chain Channel",
      "Decentralized Delta",
      "Peer-to-Peer Pool",
      "Immutable Inlet",
      "Crypto Current",
      "DeFi Depth",
      "Staking Stream",
      "Liquidity Lake",
      "Yield Yacht",
      "Smart Contract Sea",
      "Token Tide",
      "NFT Nook",
      "DAO Dock",
      "Oracle Ocean",
      "Consensus Cove",
      "Gas Fee Gulf",
      "HODL Harbor",
      "Whitepaper Waters",
      "Airdrop Aqua",
      "ICO Inlet",
      "Sharding Shore",
      "Layer 2 Lagoon",
      "Cross-Chain Creek",
      "Zero-Knowledge Zone",
    ];
    return poolNames[poolId % poolNames.length];
  }; 